# Generated by Django 3.2.9 on 2021-11-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='raw_passed',
            field=models.BooleanField(null=True),
        ),
    ]
