# Generated by Django 3.2.9 on 2021-11-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mark_raw_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='all_passed',
            field=models.BooleanField(null=True),
        ),
    ]
