# Generated by Django 3.2.9 on 2021-11-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subject_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='compulsory',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_n',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
